### ISSUE TITLE
Epic 1: Authentication

### ISSUE THREAD

**Issue by LesterCuasay** [LesterCuasay/productivity-app-api#1]
- [ ] As a **first-time user** I can **sign up** so that **I can make an account**
- [ ] As a **user** I can **sign in** so that **I can access logged in features**
- [ ] As a **user** I can **access my profile** so that **I can change my user details**
- [ ] As a **site admin** I can **see the list of users** so that **I can see how many users are signed up**
- [ ] As a **site admin** I can **access user profiles** so that **I can amend any changes the users ask for**
