### ISSUE TITLE
Epic 3: Detailed Task Comments

### ISSUE THREAD

**Issue by LesterCuasay** [LesterCuasay/productivity-app-api#12]
- [ ] As a **user** I can **add task requirements after creating a task** so that **I can check off what is still needed to do**
- [ ] As a **user** I can **attach a file** so that **I can add a draft for my task**
- [ ] As a **user** I can **change status** so that **the progress of the task can be reflected**
