### ISSUE TITLE
Epic 2: Task Creation

### ISSUE THREAD

**Issue by LesterCuasay** [LesterCuasay/productivity-app-api#7]
As a **role** I can **capability** so that **benefit**

- [ ] As a **role** I can **capability** so that **benefit**
- [ ] As a **role** I can **capability** so that **benefit**
- [ ] As a **role** I can **capability** so that **benefit**
- [ ] As a **role** I can **capability** so that **benefit**
- [ ] As a **role** I can **capability** so that **benefit**
